# Generated by Django 5.0 on 2024-03-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_staffregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
