# Generated by Django 5.0 on 2024-03-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_registration_last_login_staffregistration_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
