# Generated by Django 5.0 on 2024-03-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_registration_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='is_active',
        ),
    ]
