# Generated by Django 5.0 on 2024-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_event_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participation',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Male & Female', 'Male & Female')], default='Both', max_length=20),
        ),
    ]
