# Generated by Django 5.0 on 2024-03-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
